#!/usr/bin/env python3
"""Generate src/bridge/x64dbg_commands.inc from x64dbg's own command registrations.

Reads external/x64dbg/src/dbg/x64dbg.cpp, extracts every dbgcmdnew(...) call,
and emits a C++ header fragment containing a single raw string literal that
lists every command name, its aliases, and whether it requires an active
debugging session.

Usage:
    python tools/gen_command_reference.py [path/to/x64dbg.cpp]

Run with no arguments from the repository root to use the default path.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = REPO_ROOT / "external" / "x64dbg" / "src" / "dbg" / "x64dbg.cpp"
OUTPUT_PATH = REPO_ROOT / "src" / "bridge" / "x64dbg_commands.inc"

DBGCMDNEW_RE = re.compile(
    r'dbgcmdnew\(\s*"([^"]*)"\s*,\s*[A-Za-z_][A-Za-z0-9_]*\s*,\s*(true|false)\s*\)\s*;'
)

HEADER = """x64dbg command reference
========================

This list is generated from x64dbg's own command registrations
(dbgcmdnew calls in x64dbg.cpp), so it is exactly what the debugger accepts.
It is not a description of what each command does -- see
https://help.x64dbg.com/ for per-argument documentation.

Rules that actually cause mistakes:
- Arguments are separated by COMMAS, not spaces.
- All numbers are interpreted as HEX by default; always write an explicit
  0x prefix. A bare decimal is silently reinterpreted -- "attach 18308" is
  read as 0x18308.
- Quote any path that may contain a space or comma.
- Commands marked [debug-only] require an active debugging session and fail
  when nothing is being debugged. Commands marked [any-state] work whether
  or not a debuggee is attached.

Commands are sorted alphabetically by primary name below.

Format: primary-name [debug-only|any-state] (aliases: a, b, c)
"""


class GenerationError(Exception):
    pass


def parse_commands(source_text: str):
    commands = []
    for match in DBGCMDNEW_RE.finditer(source_text):
        names_raw, debugonly_raw = match.groups()
        names = [n.strip() for n in names_raw.split(",")]
        names = [n for n in names if n]
        if not names:
            continue
        primary, aliases = names[0], names[1:]
        commands.append((primary, aliases, debugonly_raw == "true"))
    return commands


def format_commands(commands):
    lines = []
    for primary, aliases, debugonly in sorted(commands, key=lambda c: c[0].lower()):
        state = "debug-only" if debugonly else "any-state"
        line = f"{primary} [{state}]"
        if aliases:
            line += f" (aliases: {', '.join(aliases)})"
        lines.append(line)
    return lines


def choose_delimiter(body: str) -> str:
    for delim in ("REF", "X64DBGREF", "CMDREF"):
        if f'){delim}"' not in body:
            return delim
    raise GenerationError("could not find a safe raw-string delimiter")


def main(argv):
    source_path = Path(argv[1]) if len(argv) > 1 else DEFAULT_SOURCE

    if not source_path.is_file():
        print(
            f"error: x64dbg source not found at {source_path}\n"
            "Clone x64dbg into external/ first, e.g.:\n"
            "  git clone https://github.com/x64dbg/x64dbg external/x64dbg",
            file=sys.stderr,
        )
        return 1

    source_text = source_path.read_text(encoding="utf-8", errors="strict")
    commands = parse_commands(source_text)

    if not commands:
        print(
            f"error: found no dbgcmdnew(...) registrations in {source_path}; "
            "refusing to emit an empty reference",
            file=sys.stderr,
        )
        return 1

    debugonly_count = sum(1 for _, _, d in commands if d)
    total = len(commands)

    body_lines = format_commands(commands)
    body = HEADER + "\n" + "\n".join(body_lines) + "\n"

    delimiter = choose_delimiter(body)

    output = (
        "// Generated by tools/gen_command_reference.py -- do not edit by hand.\n"
        f'inline constexpr const char* kX64dbgCommandReference = R"{delimiter}(\n'
        f"{body}"
        f'){delimiter}";\n'
    )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_bytes(output.encode("utf-8"))

    print(f"wrote {OUTPUT_PATH}")
    print(f"total commands: {total}")
    print(f"debug-only: {debugonly_count}")
    print(f"any-state: {total - debugonly_count}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
