name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build (x64)
        run: |
          mkdir package\x64\plugins
          cmake -B build64 -A x64
          cmake --build build64 --config Release
          copy build64\Release\*.dp64 package\x64\plugins\

      - name: Test (x64)
        run: ctest --test-dir build64 -C Release --output-on-failure

      - name: Build (x32)
        run: |
          mkdir package\x32\plugins
          cmake -B build32 -A Win32
          cmake --build build32 --config Release
          copy build32\Release\*.dp32 package\x32\plugins\

      - name: Test (x32)
        run: ctest --test-dir build32 -C Release --output-on-failure

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
          path: package/
